spring.application.name=SpringBootRabbitmq

# =============================================
# RABBITMQ GENERAL CONFIGURATION
# =============================================

rabbitmq.exchange.clients.name=clients_exchange
rabbitmq.exchange.gen.name=postrequests_exchange
rabbitmq.routing.key.imgs.name=imgs_routing_key
rabbitmq.routing.key.alerts.name=postalerts_routing_key
rabbitmq.routing.key.data.name=postrequests_routing_key
rabbitmq.queue.imgs.name=queue_imgs
rabbitmq.queue.data.name=postrequests

