spring.application.name=SpringBootRabbitmq

# =============================================
# RABBITMQ GENERAL CONFIGURATION
# =============================================

rabbitmq.exchange.clients.name=clients_exchange
rabbitmq.exchange.gen.name=gen_exchange
rabbitmq.routing.key.reports.name=reports_routing_key
rabbitmq.routing.key.data.name=data_routing_key
rabbitmq.queue.reports.name=queue_reports
rabbitmq.queue.data.name=data_queue

rabbitmq.client.sync.interval-ms=5000

app.batch.max-size=50
app.batch.max-wait-ms=2500